# -*- coding: utf-8 -*-
"""Ops platform constants."""
from __future__ import annotations

import threading
from collections import deque
from typing import Any, Dict, Optional

from services.ops_platform_gateway import OpsPlatformGateway

ops_gateway = OpsPlatformGateway()
_agent_metric_history_lock = threading.Lock()
_agent_metric_history: Dict[str, deque] = {}
_NODE_CONTRACT_REGISTRY_CACHE: Optional[Dict[str, Any]] = None

OPS_TRACE_LOG_KEY = "OPS_PLATFORM_TRACE_LOGS"
OPS_EVENT_LOG_KEY = "OPS_PLATFORM_EVENT_LOGS"
OPS_ALERT_SNAPSHOT_KEY = "OPS_PLATFORM_ALERT_SNAPSHOT"
OPS_TOPOLOGY_KEY = "OPS_PLATFORM_TOPOLOGY"
OPS_TOPOLOGY_REGISTRY_KEY = "OPS_PLATFORM_TOPOLOGY_REGISTRY"
OPS_TOPOLOGY_CONTENTS_KEY = "OPS_PLATFORM_TOPOLOGY_CONTENTS"
OPS_NODE_PRESETS_KEY = "OPS_PLATFORM_NODE_PRESETS"
OPS_TOPOLOGY_BLUEPRINTS_KEY = "OPS_PLATFORM_TOPOLOGY_BLUEPRINTS"
OPS_DAEMON_STATE_KEY = "OPS_PLATFORM_DAEMON_STATE"
OPS_FLOW_EXEC_KEY = "OPS_PLATFORM_FLOW_EXECUTIONS"
OPS_AGENT_REGISTRY_KEY = "OPS_PLATFORM_AGENT_REGISTRY"
OPS_AGENT_REGISTRY_V2_KEY = "OPS_PLATFORM_AGENT_REGISTRY_V2"
OPS_AGENT_METRIC_WINDOW_SEC = 3600
OPS_AGENT_METRIC_MAX_POINTS = 720
OPS_NODE_AGENT_BINDING_KEY = "OPS_PLATFORM_NODE_AGENT_BINDING"
OPS_NODE_SERVICE_BINDING_KEY = "OPS_PLATFORM_NODE_SERVICE_BINDING"
OPS_AGENT_JOBS_KEY = "OPS_PLATFORM_AGENT_JOBS"
OPS_AGENT_POLICY_KEY = "OPS_PLATFORM_AGENT_POLICY"
OPS_RUNTIME_RUNS_KEY = "OPS_PLATFORM_RUNTIME_RUNS"
OPS_CHANGE_FREEZE_KEY = "OPS_PLATFORM_CHANGE_FREEZE"
CANONICAL_LOCAL_AGENT_ID = "agent-local-cn-1"
CANONICAL_LOCAL_DEVICE_ID = "local-game-server"
DEFAULT_LOOPBACK = "127.0.0.1"
_RUNTIME_GATEWAY_PROBE_PORT = 15050
_RUNTIME_OPS_PROBE_PORT = 5504
_TOPOLOGY_BLUEPRINT_FRAMEWORK_VERSION = 2
