#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate BaaS error artifacts from packages/baas_shared/error_codes.json."""

from __future__ import annotations

import json
import os
import sys

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_SRC = os.path.join(_REPO, "packages", "baas_shared", "error_codes.json")
_DOC = os.path.join(_REPO, "docs", "baas_error_codes.md")
_CS_DIR = os.path.join(_REPO, "packages", "client_network", "baas", "Runtime", "Generated")
_CS_CODES = os.path.join(_CS_DIR, "BaasErrorCodes.cs")
_CS_CATALOG = os.path.join(_CS_DIR, "BaasErrorCatalog.cs")
_CLIENT_JSON = os.path.join(_REPO, "packages", "client_network", "baas", "Config", "error_codes.json")
_OPENAPI_ENDPOINTS = os.path.join(_CS_DIR, "BaasOpenApiEndpoints.cs")


def load_catalog() -> dict:
    with open(_SRC, "r", encoding="utf-8") as fh:
        return json.load(fh)


def write_docs(catalog: dict) -> None:
    lines = [
        "# BaaS Error Codes",
        "",
        "Single source: `packages/baas_shared/error_codes.json`. Regenerate with:",
        "",
        "```powershell",
        "py -3 scripts/generate_baas_error_artifacts.py",
        "```",
        "",
        "## Envelope",
        "",
        "```json",
        '{ "ok": false, "error_code": "BAAS_ROOM_NOT_FOUND", "error": "房间不存在", "details": {} }',
        "```",
        "",
        "## Transport codes (client network layer)",
        "",
        "| Code | 中文 | client_action | retry |",
        "|------|------|---------------|-------|",
    ]
    for code, meta in sorted((catalog.get("transport_codes") or {}).items(), key=lambda x: int(x[0])):
        lines.append(
            f"| {code} | {meta.get('message_zh', '')} | {meta.get('client_action', '')} | {meta.get('retry', False)} |"
        )
    lines.extend(["", "## Business codes", "", "| error_code | HTTP | 中文 | category | client_action | retry |", "|------------|------|------|----------|---------------|-------|"])
    for code, meta in sorted((catalog.get("codes") or {}).items()):
        lines.append(
            f"| `{code}` | {meta.get('http_status', 400)} | {meta.get('message_zh', '')} | {meta.get('category', '')} | {meta.get('client_action', '')} | {meta.get('retry', False)} |"
        )
    os.makedirs(os.path.dirname(_DOC), exist_ok=True)
    with open(_DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def write_csharp_codes(catalog: dict) -> None:
    os.makedirs(_CS_DIR, exist_ok=True)
    lines = [
        "// <auto-generated />",
        "namespace MAClient.Network.Baas",
        "{",
        "    public static class BaasErrorCodes",
        "    {",
    ]
    for code in sorted((catalog.get("codes") or {}).keys()):
        lines.append(f'        public const string {code} = "{code}";')
    lines.extend(["    }", "}"])
    with open(_CS_CODES, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def write_csharp_catalog(catalog: dict) -> None:
    json_text = json.dumps(catalog, ensure_ascii=False)
    escaped = json_text.replace("\\", "\\\\").replace('"', '\\"')
    content = f"""// <auto-generated />
using System;
using UnityEngine;

namespace MAClient.Network.Baas
{{
    public static class BaasErrorCatalog
    {{
        const string EmbeddedJson = "{escaped}";

        [Serializable]
        class Root {{ public CodeRow[] codes; public AliasRow[] message_aliases; public TransportRow[] transport_codes; }}
        [Serializable] class CodeRow {{ public string key; public string http_status; public string message_zh; public string message_en; public string client_action; public string retry; }}
        [Serializable] class AliasRow {{ public string key; public string value; }}
        [Serializable] class TransportRow {{ public string key; public string message_zh; public string client_action; }}

        static Root _cache;

        public static string ResolveCode(string codeOrMessage)
        {{
            EnsureCache();
            if (string.IsNullOrEmpty(codeOrMessage)) return BaasErrorCodes.BAAS_UNKNOWN;
            foreach (var row in _cache.codes ?? Array.Empty<CodeRow>())
            {{
                if (row.key == codeOrMessage) return codeOrMessage;
            }}
            foreach (var row in _cache.message_aliases ?? Array.Empty<AliasRow>())
            {{
                if (row.key == codeOrMessage) return row.value;
            }}
            return BaasErrorCodes.BAAS_UNKNOWN;
        }}

        public static string MessageZh(string code)
        {{
            EnsureCache();
            foreach (var row in _cache.codes ?? Array.Empty<CodeRow>())
            {{
                if (row.key == code) return row.message_zh ?? code;
            }}
            return code;
        }}

        public static string ClientAction(string code)
        {{
            EnsureCache();
            foreach (var row in _cache.codes ?? Array.Empty<CodeRow>())
            {{
                if (row.key == code) return row.client_action ?? "toast";
            }}
            return "toast";
        }}

        public static bool ShouldRetry(string code)
        {{
            EnsureCache();
            foreach (var row in _cache.codes ?? Array.Empty<CodeRow>())
            {{
                if (row.key == code) return string.Equals(row.retry, "true", StringComparison.OrdinalIgnoreCase) || row.retry == "True";
            }}
            return false;
        }}

        public static int MapToTransportCode(string code)
        {{
            if (code == BaasErrorCodes.BAAS_AUTH_TOKEN_EXPIRED || code == BaasErrorCodes.BAAS_AUTH_SESSION_INVALID) return 1008;
            if (code == BaasErrorCodes.BAAS_FRAMEWORK_NOT_DEPLOYED) return 1009;
            if (code == BaasErrorCodes.BAAS_GAMESERVER_BRIDGE_FAILED) return 1010;
            return 1007;
        }}

        static void EnsureCache()
        {{
            if (_cache != null) return;
            var wrapper = "{{\\"items\\":" + EmbeddedJson + "}}";
            // JsonUtility cannot parse top-level dict; use manual alias scan via simple parser in BaasApiResponse.
            _cache = new Root();
            _cache.codes = ParseCodeRows();
            _cache.message_aliases = ParseAliasRows();
        }}

        static CodeRow[] ParseCodeRows()
        {{
            var list = new System.Collections.Generic.List<CodeRow>();
"""
    for code, meta in sorted((catalog.get("codes") or {}).items()):
        content += f'            list.Add(new CodeRow {{ key = "{code}", http_status = "{meta.get("http_status", 400)}", message_zh = "{meta.get("message_zh", "").replace(chr(34), "")}", message_en = "{meta.get("message_en", "").replace(chr(34), "")}", client_action = "{meta.get("client_action", "toast")}", retry = "{str(meta.get("retry", False))}" }});\n'
    content += "            return list.ToArray();\n        }\n\n        static AliasRow[] ParseAliasRows()\n        {\n            var list = new System.Collections.Generic.List<AliasRow>();\n"
    for msg, code in sorted((catalog.get("message_aliases") or {}).items()):
        safe_msg = msg.replace("\\", "\\\\").replace('"', '\\"')
        content += f'            list.Add(new AliasRow {{ key = "{safe_msg}", value = "{code}" }});\n'
    content += "            return list.ToArray();\n        }\n    }\n}\n"
    with open(_CS_CATALOG, "w", encoding="utf-8") as fh:
        fh.write(content)


def write_openapi_endpoints() -> None:
    """Generate endpoint constants from registry.public_endpoints_for_features."""
    sys.path.insert(0, os.path.join(_REPO, "portals", "common", "core"))
    from services.baas.registry import FEATURE_CATALOG, public_endpoints_for_features

    flags = {row["key"]: True for row in FEATURE_CATALOG}
    endpoints = public_endpoints_for_features(flags)
    lines = [
        "// <auto-generated />",
        "namespace MAClient.Network.Baas",
        "{",
        "    /// <summary>bootstrap endpoints 映射的静态路径模板（含 {service_id} 占位符）。</summary>",
        "    public static class BaasOpenApiEndpoints",
        "    {",
        '        public const string ServiceIdPlaceholder = "{service_id}";',
    ]
    for key, path in sorted(endpoints.items()):
        const = "".join(ch if ch.isalnum() else "_" for ch in key).upper()
        lines.append(f'        /// <summary>功能键: {key}</summary>')
        lines.append(f'        public const string {const} = "{path}";')
    lines.extend(["    }", "}"])
    with open(_OPENAPI_ENDPOINTS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> int:
    catalog = load_catalog()
    os.makedirs(os.path.dirname(_CLIENT_JSON), exist_ok=True)
    with open(_CLIENT_JSON, "w", encoding="utf-8") as fh:
        json.dump(catalog, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    write_docs(catalog)
    write_csharp_codes(catalog)
    write_csharp_catalog(catalog)
    try:
        write_openapi_endpoints()
    except Exception as exc:
        print(f"[warn] openapi endpoints generation skipped: {exc}")
    print(f"[ok] docs -> {_DOC}")
    print(f"[ok] csharp -> {_CS_DIR}")
    print(f"[ok] client json -> {_CLIENT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
